<template>
  <div style='text-align: left;'>
    <h2>Nested Counters Example</h2>
    <nested-counters v-bind="counters1">
    </nested-counters>
    <h2>
      Explaination
    </h2>
    <ol style='text-align: left;'>
      <li><span style='color: blue;'>blue</span> text is counters generated by css</li>
      <li><span style='color: darkgray;'>normal</span> text is generate by simulating counters mechanism</li>
      <li>increasement of counter depth like 'doc: 1' -> 'doc: 1.0' means new nested counter is created</li>
      <li>
        counters go through inherits, resets, sets, increments, usage process sequentially,
        hover on one item to see detail process in tooltip
      </li>
      <li>
        Refer to
        <a href="https://github.com/marked42/learning-notes/blob/dev/css/css.md#counters">this</a>
        for detailed explaination on css counter internal mechanism
      </li>
    </ol>
  </div>
</template>

<script>
import {
  createElementCounter,
} from '../utils/counters'

import NestedCounters from './NestedCounters'

export default {
  name: 'CssCounters',
  components: {
    NestedCounters,
  },
  data() {
    return {
      counterConfig: {
        resets: [ { name: 'doc', value: 1 } ],
        usage: {
          counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
        },
        children: [
          {
            resets: [ { name: 'doc', value: 10 } ],
            usage: {
              counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
            },
            children: [],
          },
          {
            resets: [ { name: 'chapter', value: 1 } ],
            usage: {
              counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
            },
            children: [
              {
                resets: [ { name: 'section', value: 1 } ],
                usage: {
                  counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
                },
                children: [],
              },
              {
                increments: [ { name: 'section', value: 1 } ],
                usage: {
                  counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
                },
              },
              {
                resets: [ { name: 'section', value: 1 } ],
                usage: {
                  counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
                },
              },
              {
                resets: [ { name: 'section', value: 2 } ],
                increments: [ { name: 'section', value: 3 } ],
                usage: {
                  counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
                },
              },
            ],
          },
          {
            resets: [ { name: 'chapter', value: 10 } ],
            usage: {
              counter: [ { name: 'doc' }, { name: 'chapter' }, { name: 'section' } ],
            },
            children: [],
          },
        ],
      },
    }
  },
  computed: {
    counters1() {
      return createElementCounter(this.counterConfig, true)
    },
  },
}
</script>

<style lang="stylus" scoped>
</style>
